base/urls.py
from django.urls import path
from base import views

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_page, name='register'),

    path('users/<str:pk>/', views.user_profile, name='user-profile'),
    path('update-user/', views.update_user, name="update-user"),

    path('', views.home, name='home'),
    path('authors/<str:pk>/', views.author_profile, name='author-profile'),
    path('tales/<str:pk>/', views.tale, name='tale'),

    path('forum/', views.forum, name='forum',),
    path('delete-message/<str:pk>/', views.delete_message, name='delete-message'),

    path('create-tale/', views.create_tale, name='create-tale'),
    path('update-tale/<str:pk>/', views.update_tale, name='update-tale'),
    path('delete-tale/<str:pk>/', views.delete_tale, name='delete-tale'),
    path('tales/', views.all_tales, name='all-tales'),

    path('create-author/', views.create_author, name='create-author'),
    path('update-author/<str:pk>/', views.update_author, name='update-author'),
    path('delete-author/<str:pk>/', views.delete_author, name='delete-author'),
    path('authors/', views.all_authors, name='all-authors'),
]

fairyall/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import AbstractUser
from ckeditor.fields import RichTextField


class Country(models.Model):
    name = models.CharField(max_length=128)

    class Meta:
        verbose_name_plural = 'Countries'
        ordering = ['name']

    def __str__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=128)
    nationality = models.ForeignKey(Country, on_delete=models.CASCADE)
    bio = RichTextField()
    picture = models.ImageField(null=True, default='picture.svg')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Tale(models.Model):
    title = models.CharField(max_length=128)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    body = RichTextField()
    cover = models.ImageField(null=True, default='cover.jpg')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['author', 'created']

    def __str__(self):
        return self.title


class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=True)
    bio = RichTextField(null=True)
    picture = models.ImageField(null=True, default="avatar.svg")

    favourite_tale = models.ForeignKey(
        Tale, on_delete=models.CASCADE, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]

base/forms.py
from wsgiref.validate import validator
from django import forms
from django.contrib.auth import password_validation
from django.forms import ModelForm
from ckeditor.widgets import CKEditorWidget
from django.contrib.auth.forms import UserCreationForm
from .models import Author, Tale, User


class MyUserCreationForm(UserCreationForm):
    password1 = forms.CharField(
        label=("Парола"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=("Потвърдете паролата"),
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        strip=False,
        help_text=("Въведете същата парола!"),
    )

    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']

        labels = {'name': 'Име', 'username': 'Потребителско Име'}


class TaleForm(ModelForm):
    body = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Tale
        fields = '__all__'
        labels = {'title': 'Заглавие', 'author': 'Автор',
                  'body': 'Съдържание', 'cover': 'Корица'}


class AuthorForm(ModelForm):
    bio = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Author
        fields = '__all__'
        labels = {'name': 'Име', 'nationality': 'Националност',
                  'bio': 'Биография', 'picture': 'Снимка'}


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['picture', 'name', 'username',
                  'email', 'favourite_tale', 'bio']
        labels = {'picture': 'Снимка', 'name': 'Име',
                  'username': 'Потребителско име', 'email': 'Email', 'bio': 'Нещо за вас', 'favourite_tale': 'Любима приказка'}

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from .forms import MyUserCreationForm, AuthorForm, TaleForm, UserForm
from .models import User, Country, Author, Tale, Message
import datetime, random


def login_page(request):
    page = 'login'

    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get('email')
        except:
            messages.error(request, 'Потребителят не съществува')

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')

        else:
            messages.error(request, 'Пощата или паролата са неправилни')

    context = {'page': page}
    return render(request, 'base/login_register.html', context)


def logout_user(request):
    logout(request)
    return redirect('home')


def register_page(request):
    form = MyUserCreationForm()

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            login(request, user)
            return redirect('home')

        else:
            messages.error(request, 'Настъпи някаква грешка! Опитайте отново!')

    context = {'form': form}

    return render(request, 'base/login_register.html', context)


def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    all_tales = Tale.objects.all()
    tales_count = all_tales.count()

    x = datetime.datetime.today().strftime("%Y:%m:%d")
    random.seed(x)
    random1, random2, random3 = random.sample(range(1, tales_count-1), 3)

    tale1 = Tale.objects.get(id=random1)
    tale2 = Tale.objects.get(id=random2)
    tale3 = Tale.objects.get(id=random3)

    authors = Author.objects.all()[0:5]
    user_messages = Message.objects.all()[0:7]

    context = {'tale1': tale1, 'tale2': tale2, 'tale3': tale3, 'authors': authors,
               'user_messages': user_messages, 'tales_count': tales_count}
    return render(request, 'base/home.html', context)


def author_profile(request, pk):
    author = Author.objects.get(id=pk)
    authors = Author.objects.all()[0:5]
    author_tales = Tale.objects.filter(Q(author__name__contains=author))

    all_tales = Tale.objects.all()
    tales_count = all_tales.count()

    context = {'author': author, 'authors': authors,
               'author_tales': author_tales, 'tales_count': tales_count}
    return render(request, 'base/author.html', context)


def tale(request, pk):
    tale = Tale.objects.get(id=pk)
    tales = Tale.objects.filter(Q(author__name__contains=tale.author))[0:3]

    context = {'tale': tale, 'tales': tales}
    return render(request, 'base/tale.html', context)


def all_tales(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    tales = Tale.objects.filter(
        Q(author__name__icontains=q) |
        Q(title__icontains=q.lower())
    )

    context={'tales': tales}
    return render(request, 'base/all_tales.html', context)


def user_profile(request, pk):
    user = User.objects.get(id=pk)
    user_messages = user.message_set.all()[0:3]
    authors = Author.objects.all()[0:5]

    all_tales = Tale.objects.all()
    tales_count = all_tales.count()

    context = {'user': user, 'user_messages': user_messages, 'authors': authors, 'tales_count': tales_count}
    return render(request, 'base/profile.html', context)


@login_required(login_url='login')
def update_user(request):
    user = request.user
    form = UserForm(instance=user)

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('user-profile', pk=user.id)

    return render(request, 'base/creation-form.html', {'form': form})


@login_required(login_url='login')
def forum(request):
    user_messages = Message.objects.all()[0:100]

    if request.method == 'POST':
        message = Message.objects.create(
            user=request.user,
            body=request.POST.get('body')
        )
        if message.body == "":
            message.delete()
        return redirect('forum')

    context = {'user_messages': user_messages}
    return render(request, 'base/forum.html', context)


@login_required(login_url='login')
def delete_message(request, pk):
    message = Message.objects.get(id=pk)

    if request.user != message.user:
        return HttpResponse('Нямате достъп до тази страница')

    if request.method == 'POST':
        message.delete()
        return redirect('forum')
    return render(request, 'base/delete.html', {'obj': message})


# TODO: add a view for a staff members page

@staff_member_required
def create_tale(request):
    title = 'tale-create'
    form = TaleForm()

    if request.method == 'POST':
        form = TaleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # TODO: redirect to a page for the staff members
            return redirect('home')
        else:
            messages.error(request, 'Неуспешно създаване на приказка')

    context = {'form': form, 'title': title}
    return render(request, 'base/creation-form.html', context)


@staff_member_required
def update_tale(request, pk):
    title = 'tale-update'
    tale = Tale.objects.get(id=pk)
    form = TaleForm(instance=tale)

    if not request.user.is_staff:
        return HttpResponse('Нямате достъп до тази страница!')

    if request.method == 'POST':
        form = TaleForm(request.POST, request.FILES, instance=tale)
        if form.is_valid():
            form.save()
            # TODO: redirect to a page for the staff members
            return redirect('home')

    context = {'form': form, 'title': title}
    return render(request, 'base/creation-form.html', context)


@staff_member_required
def delete_tale(request, pk):
    tale = Tale.objects.get(id=pk)

    if not request.user.is_staff:
        return HttpResponse('Нямате достъп до тази страница!')

    if request.method == 'POST':
        tale.delete()
        return redirect('home')

    context = {'obj': tale}
    return render(request, 'base/delete.html', context)


@staff_member_required
def create_author(request):
    title = 'author-create'
    form = AuthorForm()

    if request.method == 'POST':
        form = AuthorForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # TODO: redirect to a page for the staff members
            return redirect('home')
        else:
            messages.error(request, 'Неуспешно създаване на автор')

    context = {'form': form, 'title': title}
    return render(request, 'base/creation-form.html', context)


@staff_member_required
def update_author(request, pk):
    title = 'author-update'
    author = Author.objects.get(id=pk)
    form = AuthorForm(instance=author)

    if not request.user.is_staff:
        return HttpResponse('Нямате достъп до тази страница!')

    if request.method == 'POST':
        form = AuthorForm(request.POST, request.FILES, instance=tale)
        if form.is_valid():
            form.save()
            # TODO: redirect to a page for the staff members
            return redirect('home')

    context = {'form': form, 'title': title}
    return render(request, 'base/creation-form.html', context)


@staff_member_required
def delete_author(request, pk):
    author = Author.objects.get(id=pk)

    if not request.user.is_staff:
        return HttpResponse('Нямате достъп до тази страница!')

    if request.method == 'POST':
        author.delete()
        return redirect('home')

    context = {'obj': author}
    return render(request, 'base/delete.html', context)


def all_authors(request):
    authors = Author.objects.all()
    all_tales = Tale.objects.all()
    tales_count = all_tales.count()

    context={'authors': authors, 'tales_count': tales_count}
    return render(request, 'base/all_authors.html', context)

base/templates/base/all_authors.html
{% extends 'main.html' %}

{% block content %}
<div class="container vertical-center col-lg-8 col-md-6 justify-content-center align-items-center">
    <div class="d-grid">
        <div class="bg-blue text-center rounded-top">
            <h2 class="text-cyan">Автори</h2>
            <p><a class="text-decoration-none text-cyan link-grey" href="{% url 'all-tales' %}">приказки</a>: <span>{{tales_count}}</span></p>
        </div>
        <div class="bg-grey rounded-bottom">
            {% for author in authors %}
            {% if author.name != "Български Народни Приказки" and author.name != "Приказки от 1001 нощ" %}
            <div class="row align-items-center justify-content-center text-left m-3">
                <div class="col-8">
                    <h4>
                        <a class="text-blue link-cyan text-decoration-none" href="{% url 'author-profile' author.id %}">
                            {{author.name}}
                        </a>
                    </h4>
                </div>

                <div class="col-3 text-center mx-2">
                    <h4 class="border-radius-5 bg-blue text-cyan">
                        {{author.tale_set.all.count}}
                    </h4>
                </div>
                
            </div>
            <hr class="mx-3">
            
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

base/templates/base/all_tales.html
{% extends 'main.html' %} {% block content %}
<div class="container col-md-9">
    <div class="m-3 d-lg-none d-xl-block d-xl-none">
        <form class="d-flex" role="search" method="GET" action="{% url 'all-tales' %}">
            <input class="form-control" name="q" type="search" placeholder="Търсете приказки" />
            <button class="btn btn-blue text-cyan" type="submit">Търси</button>
        </form>
    </div>

    <div class="row d-flex">
        {% for tale in tales %}
        <div class="col-sm-12 col-md-6 col-lg-4 my-3">
            <div class="card bg-blue text-cyan text-center">
                <img class="card-img-top" width="100px" height="400px" src="{{tale.cover.url}}" alt="Card image cap" />
                <div class="card-body position-relative">
                    {% if tale.title|length > 23 %}
                    <h5 class="card-title h6">{{tale.title|title}}</h5>
                    {% else %}
                    <h5 class="card-title">{{tale.title|title}}</h5>
                    {% endif %}
                    <a class="card-text text-grey link-cyan text-decoration-none"
                        href="{% url 'author-profile' tale.author.id %}"><small
                            class="">{{tale.author.name}}</small></a>
                    <br />
                    <a class="btn btn-outline-cyan mt-3" href="{% url 'tale' tale.id %}">
                        ПРОЧЕТИ
                    </a>

                    {% if request.user.is_staff %}
                    <a href="{% url 'update-tale' tale.id %}">
                        <div class="position-absolute top-0 pt-1 px-1 start-0">
                            <svg enable-background="new 0 0 24 24" height="23" viewBox="0 0 23 23" width="23"
                                xmlns="http://www.w3.org/2000/svg">
                                <title>edit</title>
                                <g>
                                    <path
                                        d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                                </g>
                                <g>
                                    <g>
                                        <path
                                            d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z" />
                                    </g>
                                    <g>
                                        <path
                                            d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z" />
                                    </g>
                                </g>
                            </svg>
                        </div>
                    </a>

                    <a href="{% url 'delete-tale' tale.id %}">
                        <div class="text-right position-absolute top-0 end-0 pt-1 px-1">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="25" height="25"
                                viewBox="0 0 32 32">
                                <title>remove</title>
                                <path
                                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                                </path>
                            </svg>
                        </div>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

base/templates/base/author.html
{% extends 'main.html' %}

{% block content %}

<div class="d-flex row container-fluid mt-4 px-0 mx-0 mb-2">
    <!-- Authors section -->
    <div class="col mx-2 bg-blue text-center rounded d-md-none d-lg-block d-sm-none d-md-block d-none d-sm-block">
        {% include 'base/authors_section.html' %}

        {% include 'base/site_goal.html' %}
    </div>
    <!-- End -->

    <!-- Author's Information -->
    <div class=" justify-content-center align-items-center col-lg-6">
        <div class="text-blue mb-5 text-center">
            <img class="rounded" width="300px" height="400px" src="{{author.picture.url}}" />
            <h1 class="m-auto">{{author.name}}</h1>

            {% if request.user.is_staff %}
            <a class="btn btn-outline-blue mt-2" href="{% url 'update-author' author.id %}">РЕДАКТИРАЙ</a>
            {% endif %}
        </div>

        <h5 class="text-blue text-justify">{{author.bio|safe}}</h5>

    </div>
    <!-- End -->
    <!-- Author's tales section -->
    <div class="col bg-blue mx-2 rounded d-md-none d-lg-block d-sm-none d-md-block d-none d-sm-block">
        {% include 'base/authors_tales_section.html' %}
    </div>
    <!-- End -->
</div>

{% endblock %}

base/templates/base/authors_section.html
<div class="bg-blue p-2 border-rounded-top">
    <h2>Автори</h2>
    <p>приказки: <span>{{tales_count}}</span></p>
</div>
<div class="bg-grey rounded-top py-3 mb-2 rounded-bottom">
    {% for a in authors %}
    {% if a.name != "Български Народни Приказки" and a.name != "Приказки от 1001 нощ" %}
    <div class="row align-items-center justify-content-center text-left py-2">
        <div class="col-8">
            <h4>
                <a class="text-blue link-cyan text-decoration-none" href="{% url 'author-profile' a.id %}">
                    {{a.name}}
                </a>
            </h4>
        </div>

        <div class="col-3 text-center mx-2">
            <h4 class="border-radius-5 bg-blue text-cyan">
                {{a.tale_set.all.count}}
            </h4>
        </div>
    </div>
    <hr>
    {% endif %}
    {% endfor %}

    <div calss="text-center">
        <a class="link-blue btn btn-cyan text-blue text-decoration-underlined" href="{% url 'all-authors' %}">ОЩЕ</a>
    </div>
</div>

base/templates/base/authors_tales_section.html
<div class="bg-blue rounded-top text-center p-2">
    <h2>Приказки от автора</h2>
</div>
<div class="bg-grey py-3 mb-2 rounded">
    {% for tale in author_tales %}
    <div class="border-blue d-block rounded m-2 p-2">
        <div class="row">
            <div class="col-3">
                <img class="profile-pic d-block" width="60px" height="60px" src="{{tale.cover.url}}" />
            </div>
            <div class="col my-auto">
                <strong>
                    <h5>
                        <a class="link-cyan text-decoration-none text-blue"
                            href="{% url 'tale' tale.id %}">{{tale.title|title}}
                        </a>
                    </h5>
                </strong>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

base/templates/base/creation-form.html
{% extends 'main.html' %}

{% block content %}
<div class="container-fluid col-lg-6 my-3 col-sm-10 justify-content-center align-items-center">
    <div class="d-grid">
        <div class="d-flex bg-blue pt-1 rounded-top">
            <a class="mx-3" href="{{request.META.HTTP_REFERER}}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 32 32">
                    <title>arrow-left</title>
                    <path
                        d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                    </path>
                </svg>
            </a>
            {% if title == 'tale-create' %}
            <h4>Добавете приказка</h4>
            {% elif title == 'tale-update' %}
            <h4>Редактирайте приказка</h4>
            {% elif title == 'author-create' %}
            <h4>Добавете автор</h4>
            {% elif title == 'author-update' %}
            <h4>Редактирайте автор</h4>
            {% else %}
            <h4>Редактирайте продила си</h4>
            {% endif %}
        </div>

        <div class="rounded-bottom">
            <form class="form-control bg-grey text-cyan" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <!-- {{form.media}}
                {{form.as_p}} -->
                {% for field in form %}
                <div class="d-grid my-4 h-75 form_group">
                    <label for="profile_pic py-3">{{field.label}}</label>
                    {{field}}
                </div>
                {% endfor %}

                <a class="btn btn-outline-blue" href="{{request.META.HTTP_REFERER}}">Отказ</a>
                {% if title == 'tale-create' or title == 'author-create' %}
                <button class="btn btn-blue text-cyan border-cyan" type="submit">Създай</button>
                {% else %}
                <button class="btn btn-blue text-cyan border-cyan" type="submit">Редактирай</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}
<div class="container vertical-center col-8 justify-content-center align-items-center">
    <div class="d-grid">
        <div class="d-flex bg-blue pt-1 rounded-top">
            <a class="mx-3" href="{{request.META.HTTP_REFERER}}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 32 32">
                    <title>arrow-left</title>
                    <path
                        d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                    </path>
                </svg>
            </a>
            <h5 class="text-cyan">Върнете се</h5>
        </div>
        <div class="bg-grey pt-5 rounded-bottom">
            <form class="text-center px-4" method="POST" action="">
                {% csrf_token %}
                <div>
                    <p class="text-cyan">Сигурни ли сте, че искате да изтриете "{{obj}}"?</p>
                </div>

                <div class="py-5">
                    <input class="btn btn-blue text-cyan" type="submit" value="Потвърди" />
                </div>

            </form>
        </div>
    </div>
</div>
{% endblock %}

base/templates/base/forum.html
{% extends 'main.html' %}

{% block content %}
<div class="container d-grid mt-4 justify-content-center align-items-center">
    <div class="text-center col-7 justify-content-center align-items-center m-auto">
        <h2 class="text-blue">ФОРУМ</h2>
        <h5 class="text-grey  mb-0">Споделете с останилите мнението си по различни въпроси</h5>
        <small class="text-grey mt-0">(показват се последните 100 съобщения)</small>
    </div>

    <div class="m-auto w-50 mt-5">
        <form action="" method="POST">
            {% csrf_token %}
            <input class="form-control border-grey" name="body" placeholder="Вашият коментар..." />
        </form>
    </div>

    <div class="row justify-content-center align-items-center">
        {% for message in user_messages %}
        <div class="bg-grey border-blue col-lg-7 col-sm-5 rounded m-2 p-2">
            {% if request.user == message.user %}
            <div class="position-relative">
                <a href="{% url 'delete-message' message.id %}">
                    <div class="text-right position-absolute top-0 end-0">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="28" height="28"
                            viewBox="0 0 32 32">
                            <title>remove</title>
                            <path
                                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                            </path>
                        </svg>
                    </div>
                </a>
            </div>
            {% endif %}

            <div class="d-flex">
                <div class="mx-1">
                    <img class="profile-pic d-block" width="40px" height="40px" src="{{message.user.picture.url}}" />
                </div>
                <div>
                    <strong>
                        <a class="link-cyan text-decoration-none text-blue"
                            href="{% url 'user-profile' message.user.id %}">@{{message.user.username}}
                        </a>
                    </strong>
                    <small>
                        коментира:
                    </small>
                    <br>
                    <small>{{message.created|timesince}} ago</small>
                </div>
            </div>
            <br>
            <p class="bg-blue text-left rounded p-2 my-1">
                {{message.body|safe}}
            </p>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

base/templates/base/login_register.html
{% extends 'main.html' %}

{% block content %}
{% if page == 'login' %}

<div class="container-fluid vertical-center col-8 justify-content-center align-items-center">
    <div class="d-grid bg-blue rounded">
        <div>
            <h2 class="text-center text-cyan">Вход</h2>
            <form class="form-control bg-grey" method="POST" action="">
                {% csrf_token %}

                <div class="form_group">
                    <label class="text-cyan">Email:</label>
                    <input name="email" type="email" />
                </div>
                <br>
                <div class="form_group">
                    <label class="text-cyan">Парола:</label>
                    <input name="password" type="password" />
                </div>

                <div class="text-center my-3">
                    <button class="btn btn-outline-blue" type="submit">Вход</button>
                </div>
            </form>
        </div>

        <div class="text-center my-3 py-0">
            <p class="text-cyan">Нямате профил?</p>
            <a class="text-decoration-none text-grey link-cyan" href="{% url 'register' %}">Регистрирайте се</a>
        </div>
    </div>
</div>

{% else %}
<div class="container-fluid vertical-center col-8 justify-content-center align-items-center">
    <div class="d-grid bg-blue rounded">
        <div>
            <h2 class="text-center text-cyan">Регистрация</h2>
            <form class="form-control bg-grey" method="POST" action="">
                {% csrf_token %}
    
                {% for field in form %}
                <div class="form_group">
                    <label class="text-cyan">{{field.label}}</label>
                    {{field}}
                </div>
                {% endfor %}
    
                <div class="text-center my-3">
                    <button class="btn btn-outline-blue" type="submit">Регистрация</button>
                </div>
            </form>
        </div>
    
        <div class="text-center my-3 py-0">
            <p class="text-cyan">Вече имате профил?</p>
            <a class="text-decoration-none text-grey link-cyan" href="{% url 'login' %}">Влез в него</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

base/templates/base/site_goal.html
<div class="bg-blue p-2 mt-2 rounded-top">
    <h2>Цел на сайта</h2>
</div>
<div class="bg-grey rounded-top py-3 mb-2 rounded-bottom">
    <p class="text-blue px-2">
        Здравейте, дарги читатели! Добре дошли в сайта с любими приказки за малки и големи - "FairyAll"!
        Идеята за сайта дойде още през 2018 година. Замислих се каква голяма роля играят съвременните технолии
        в нашия живот и как децата още преди да могат да говорят вече имат достъп до мобилни устройства. Книгите
        като че ли остават на заден план. И за да не се губи
        връзката на човека с четенето, реших да създам този сайт - място, на което можем да се докоснем до
        магията
        на приказките, да се потопим в един по-спокоен свят, изпълнен със мечти и спомени. Нека покажем на
        децата (а и на възрастните, които са позабравили магията на приказките), че четенето може да бъде
        интересно и увлекателно! Приятно четене!
    </p>
</div>